name: Publish r-dsci-100 on DockerHub
on: 
  push: 
    paths: 
      - 'rm-merge-shortcut/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ubcdsci/rm-merge-shortcut
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: rm-merge-shortcut
