name: Publish r-dsci-100 on DockerHub
on: 
  push: 
    paths: 
      - 'r-dsci-100/Dockerfile'
      - 'r-dsci-grading/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: bump
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.bump.outputs.new_tag }}
        release_name: ${{ steps.bump.outputs.new_tag }}
        body: |
          Changes in this Release
          - Rebuilt r-dsci-100 Docker image and published to DockerHub with new tag
          - Rebuilt r-dsci-grading Docker image and published to DockerHub with new tag
        draft: false
        prerelease: false
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ubcdsci/r-dsci-100
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: r-dsci-100
        tags: "latest,${{ steps.bump.outputs.new_tag }}"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ubcdsci/r-dsci-grading
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: r-dsci-grading
        tags: "latest,${{ steps.bump.outputs.new_tag }}"
